#!/bin/sh

# Expected JSON:
# {
# 	"volume_id": string, # Required
# 	"capacity_range", # Required
# 	"secrets": map[string]string,
# 	"volume_capability"
# }

input="$(cat)"

arg() {
	jq -r "$1" <<EOF
$input
EOF
}

jq -n '$ARGS.named'
