#!/bin/sh

# Expected JSON:
# {
# 	"volume_capabilities": list...,
# 	"parameters": map[string]string,
# 	"accessibility_topology"
# }

input="$(cat)"

arg() {
	jq -r "$1" <<EOF
$input
EOF
}

jq -n '$ARGS.named'
