#!/bin/sh

# Expected JSON:
# {
# 	"volume_id": string, # Required
# 	"volume_path": string, # Required
# 	"capacity_range",
# 	"staging_target_path": string,
# 	"volume_capability",
# 	"secrets": map[string]string
# }

input="$(cat)"

arg() {
	jq -r "$1" <<EOF
$input
EOF
}

jq -n '$ARGS.named'
